name    'jhoblitt-autofsck'
version '1.0.1'

author 'Joshua Hoblitt <jhoblitt@cpan.org>'
license 'Apache'
project_page 'https://github.com/jhoblitt/puppet-autofsck'
source 'https://github.com/jhoblitt/puppet-autofsck.git'
summary 'Enable unattended fsck on boot'
description 'Enable unattended fsck on boot'
dependency 'puppetlabs/stdlib', '>= 3.0.0'
